spring:
  application:
    name: user-service
  redis:
    host: 192.168.0.188
    port: 6379
    timeout: 3000
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

server:
  port: 8672
  discovery-port: 8671
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8671/eureka/